# Kitty configuration
# See https://sw.kovidgoyal.net/kitty/conf/

# Theme: Aura Dracula Spirit Soft
include themes/aura.conf

# Font
font_family        Ubuntu Mono
font_size          13.0

# Window
hide_window_decorations yes
window_padding_width    6
background_opacity      0.8
confirm_os_window_close 0
remember_window_size    no

# Scrollback
scrollback_lines   10000

# Bell
enable_audio_bell  no

# Tabs
tab_bar_edge          top
tab_bar_style         powerline
tab_powerline_style   slanted


