# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- type: rprompt
  overflow: hidden
  segments:
  - properties:
      cache_duration: none
      threshold: 1
    template: "{{ .FormattedMs }}"
    foreground: yellow
    background: transparent
    type: executiontime
    style: plain
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
      home_icon: "\uf015 "
      style: agnoster_short
    template: "{{ .Path }} "
    foreground: "#77E4F7"
    type: path
  - properties:
      cache_duration: none
      fetch_status: true
    template: "<#ffffff>on</> {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} \uf044 {{end}} "
    foreground: "#C678DD"
    type: git
    style: plain
  - properties:
      cache_duration: none
      fetch_version: true
    template: " \uf3d3 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }} {{ .Full }} "
    foreground: "#98C379"
    type: node
    style: plain
  newline: true
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: "➜  "
    foreground: "#63F08C"
    type: text
    style: plain
version: 3
