# current machine's name, optional; it can be used to filter settings or in the commit message
hostname: ""
profile: main
# sync on remote git
repository:
  type: git
  url: git@github.com:Mastermindzh/code-settings.git
  branch: master
